### PR TITLE
Spanish typos and grammar fixes

### PR DESCRIPTION
**Pull request by NachoKai**

### CODE REVIEW

**Comment by ahmadabdolsaheb** [comment]
cc @RafaelDavisH

**Review by RafaelDavisH — APPROVED** [review]
LGTM - all the corrections are great and proper Spanish. Thank you @NachoKai for catching that and for making the PR

**Comment by nhcarrigan** [comment]
@NachoKai this has a conflict - would you mind rebasing this against the current state of the `main` branch? 

If you have any questions about that process, let us know. 🙂

**Comment by NachoKai** [comment]
> @NachoKai this has a conflict - would you mind rebasing this against the current state of the `main` branch?
> 
> If you have any questions about that process, let us know. 🙂

Done!

**Review by nhcarrigan — APPROVED** [review]
LGTM~! 🥳 

Congratulations on your first pull request to this project! We look forward to future contributions!

**Pull request merged**
